---
title: "Análisis de Indicadores con Importancia Economica"
author: "Lizeth Jerez y Nicolas Arrieta"
date: "22/2/2020"
output: html_document
---

## Lectura BD

```{r}
library(tidyverse)
library(DT)
```

```{r}
BaseDatos <- read.csv(file = "SECOP_I_IPS_Depurada.CSV", nrows = 100000, stringsAsFactors = FALSE)
indicadorIE <- read.csv(file = "indicador_importancia_economica.csv",encoding = "UTF-8",
                        stringsAsFactors = FALSE, sep = ";")

nombresInd <- c("codigo_departamento", "codigo_municipio", "departamento", "municipio",
                "grado_importancia", "valor_agregado", "peso_relativo")
names(indicadorIE) <- nombresInd

```


## Crecion de variables por departamento

```{r}
variablesMunicipio <- BaseDatos %>% group_by(municipio_ejecucion) %>% 
  summarise(numero_contratos = n(), numero_entidades = n_distinct(nit_entidad), 
                                    numero_contratistas = n_distinct(id_contratista_2)) 
```

```{r}
IndicadirIE_Depar <- indicadorIE %>% group_by(departamento) %>% 
  summarise(valor_agregado_prom = mean(valor_agregado)) %>%filter(!is.na(valor_agregado_prom))
```

```{r}
IndicadirIE_Municipio <- indicadorIE %>% group_by(municipio) %>% 
  summarise(valor_agregado_prom = mean(valor_agregado)) %>%filter(!is.na(valor_agregado_prom))
```

```{r}
indice_IHH_frec_Mun <- BaseDatos %>%
      group_by(municipio_ejecucion, id_contratista_2) %>%
      summarise(total = n()) %>% 
      group_by(municipio_ejecucion) %>% 
      mutate(total_municipio = sum(total),
         indice_municipio = ((total/total_municipio)*100)^2) %>% 
      group_by(municipio_ejecucion) %>% 
      summarise(IHH_frecuencia = sum(indice_municipio))
```


```{r}

indice_IHH_valor_Mun <- BaseDatos %>%
      group_by(municipio_ejecucion, id_contratista_2) %>%
      summarise(total = sum(valor_total)) %>% 
      group_by(municipio_ejecucion) %>% 
      mutate(total_municipio = sum(total),
         indice_municipio = ((total/total_municipio)*100)^2) %>% 
      group_by(municipio_ejecucion) %>% 
      summarise(IHH_valor = sum(indice_municipio))
```

```{r}
variablesMunicipio <- merge(x = variablesMunicipio, y = indice_IHH_frec_Mun, by.x = "municipio_ejecucion",
                                by.y = "municipio_ejecucion")

variablesMunicipio <- merge(x = variablesMunicipio, y = indice_IHH_valor_Mun, by.x = "municipio_ejecucion",
                                by.y = "municipio_ejecucion")
```

```{r}
indice_DN_frec_Mun <- BaseDatos %>%
      group_by(municipio_ejecucion, id_contratista_2) %>%
      summarise(total = n()) %>% 
      group_by(municipio_ejecucion) %>% 
      mutate(total_municipio = sum(total),
         indice_municipio = total*(total-1)) %>% 
      group_by(municipio_ejecucion) %>% 
      summarise(DN = sum(indice_municipio)/(mean(total_municipio)*(mean(total_municipio)-1)))

variablesMunicipio <- merge(x = variablesMunicipio, y = indice_DN_frec_Mun, by.x = "municipio_ejecucion",
                                by.y = "municipio_ejecucion")
```


