---
title: "Análisis de Indicadores con Importancia Economica"
author: "Lizeth Jerez y Nicolas Arrieta"
date: "22/2/2020"
output: 
  html_document:
    toc: true
    number_sections: true
---

## Lectura BD

```{r warning=FALSE, error=FALSE}
library(tidyverse)
library(DT)
library(GGally)
```

```{r}
BaseDatos <- read.csv(file = "SECOP_I_Correlacion.CSV", stringsAsFactors = FALSE)
```


## Crecion de variables por departamento

```{r}
variablesMunicipio <- BaseDatos %>% group_by(anno_firma, municipio_ejecucion_2) %>% 
  summarise(numero_contratos = n(), 
            numero_entidades = n_distinct(nit_entidad),
            numero_contratistas = n_distinct(id_contratista_2),
            grado_importancia = mean(grado_importancia_economica),
            valor_agregado = mean(valor_agregado),
            peso_relatico_municipal = mean(peso_relatico_municipal))

datatable(variablesMunicipio)
```


```{r}
indice_IHH_frec_Mun <- BaseDatos %>%
      group_by(anno_firma, municipio_ejecucion_2, id_contratista_2) %>%
      summarise(total = n()) %>% 
      group_by(anno_firma, municipio_ejecucion_2) %>% 
      mutate(total_municipio = sum(total),
         indice_municipio = ((total/total_municipio))^2) %>% 
      group_by(anno_firma, municipio_ejecucion_2) %>% 
      summarise(IHH_frecuencia = sum(indice_municipio))
```


```{r}

indice_IHH_valor_Mun <- BaseDatos %>%
      group_by(anno_firma, municipio_ejecucion_2, id_contratista_2) %>%
      summarise(total = sum(valor_total)) %>% 
      group_by(anno_firma, municipio_ejecucion_2) %>% 
      mutate(total_municipio = sum(total),
         indice_municipio = ((total/total_municipio))^2) %>% 
      group_by(anno_firma, municipio_ejecucion_2) %>% 
      summarise(IHH_valor = sum(indice_municipio))
```

```{r}
variablesMunicipio <- merge(x = variablesMunicipio, y = indice_IHH_frec_Mun, by.x = c("anno_firma", "municipio_ejecucion_2"),
                                by.y = c("anno_firma", "municipio_ejecucion_2"))

variablesMunicipio <- merge(x = variablesMunicipio, y = indice_IHH_valor_Mun, by.x = c("anno_firma","municipio_ejecucion_2"),
                                by.y = c("anno_firma", "municipio_ejecucion_2"))
```

```{r}
indice_DN_frec_Mun <- BaseDatos %>%
      group_by(anno_firma, municipio_ejecucion_2, id_contratista_2) %>%
      summarise(total = n()) %>% 
      group_by(anno_firma, municipio_ejecucion_2) %>% 
      mutate(total_municipio = sum(total),
         indice_municipio = total*(total-1)) %>% 
      group_by(anno_firma, municipio_ejecucion_2) %>% 
      summarise(DN = sum(indice_municipio)/(mean(total_municipio)*(mean(total_municipio)-1)))

variablesMunicipio <- merge(x = variablesMunicipio, y = indice_DN_frec_Mun, by.x = c("anno_firma", "municipio_ejecucion_2"),
                                by.y = c("anno_firma", "municipio_ejecucion_2"))

variablesMunicipio <- variablesMunicipio %>% filter(numero_contratos > 10)

variablesMunicipio <- variablesMunicipio %>% arrange(grado_importancia, desc(IHH_valor))

```

## Resultado

```{r}
datatable(variablesMunicipio)
# write.csv(x = variablesMunicipio, file = "IndicadoresMunicipios.csv")
```


```{r}
ggplot(data = variablesMunicipio, aes(x = log(valor_agregado), y = log(IHH_frecuencia), color = anno_firma)) + geom_point()
```

```{r}
ggplot(data = variablesMunicipio, aes(x = factor(grado_importancia), y = IHH_frecuencia, color = anno_firma)) + geom_boxplot()
```

En este caso existe una posible relacion


```{r}
v1 <- variablesMunicipio %>% filter(!is.na(valor_agregado))
modelo1 <- lm(log(IHH_frecuencia)~log(valor_agregado), data=v1) 
summary(modelo1)
```

```{r}
ggplot(data = variablesMunicipio, aes(x = log(numero_contratos), y = log(IHH_frecuencia), color = anno_firma)) + geom_point()
```


```{r}
modelo2 <- lm(log(IHH_frecuencia)~log(numero_contratistas)*log(numero_contratos), data=variablesMunicipio) 
summary(modelo2)
```

```{r}

ggpairs(datos, lower = list(continuous = "smooth"),
        diag = list(continuous = "bar"), axisLabels = "none")
```
