---
title: "Análisis de Indicadores con Importancia Economica"
author: "Lizeth Jerez y Nicolas Arrieta"
date: "22/2/2020"
output: 
  html_document:
    toc: true
    number_sections: true
---

## Lectura BD

```{r warning=FALSE, error=FALSE}
library(tidyverse)
library(DT)
```

```{r}
BaseDatos <- read.csv(file = "SECOP_I_Correlacion.CSV", stringsAsFactors = FALSE)
```


## Creacion de variables por departamento

```{r}
variablesFamilia <- BaseDatos %>% group_by(nombre_familia) %>% 
  summarise(numero_contratos = n(), 
            numero_entidades = n_distinct(nit_entidad),
            numero_contratistas = n_distinct(id_contratista_2),
            contratos_cerrados = sum(proceso_abierto),
            contratos_adicion =  sum(adicion))

variablesFamilia$contratos_cerrados <- variablesFamilia$contratos_cerrados/variablesFamilia$numero_contratos
variablesFamilia$contratos_adicion <- variablesFamilia$contratos_adicion/variablesFamilia$numero_contratos

datatable(variablesFamilia)
```


```{r}
indice_IHH_frec_Mun <- BaseDatos %>%
      group_by(nombre_familia, id_contratista_2) %>%
      summarise(total = n()) %>% 
      group_by(nombre_familia) %>% 
      mutate(total_municipio = sum(total),
         indice_municipio = ((total/total_municipio)*100)^2) %>% 
      group_by(nombre_familia) %>% 
      summarise(IHH_frecuencia = sum(indice_municipio))
```


```{r}

indice_IHH_valor_Mun <- BaseDatos %>%
      group_by(nombre_familia, id_contratista_2) %>%
      summarise(total = sum(valor_total)) %>% 
      group_by(nombre_familia) %>% 
      mutate(total_municipio = sum(total),
         indice_municipio = ((total/total_municipio)*100)^2) %>% 
      group_by(nombre_familia) %>% 
      summarise(IHH_valor = sum(indice_municipio))
```

```{r}
variablesFamilia <- merge(x = variablesFamilia, y = indice_IHH_frec_Mun, by.x = "nombre_familia",
                                by.y = "nombre_familia")

variablesFamilia <- merge(x = variablesFamilia, y = indice_IHH_valor_Mun, by.x = "nombre_familia",
                                by.y = "nombre_familia")
```

```{r}
indice_DN_frec_Mun <- BaseDatos %>%
      group_by(nombre_familia, id_contratista_2) %>%
      summarise(total = n()) %>% 
      group_by(nombre_familia) %>% 
      mutate(total_municipio = sum(total),
         indice_municipio = total*(total-1)) %>% 
      group_by(nombre_familia) %>% 
      summarise(DN = sum(indice_municipio)/(mean(total_municipio)*(mean(total_municipio)-1)))

variablesFamilia <- merge(x = variablesFamilia, y = indice_DN_frec_Mun, by.x = "nombre_familia",
                                by.y = "nombre_familia")

variablesFamilia <-  variablesFamilia %>% filter(numero_contratos > 3)

variablesFamilia$puntaje_concentracion <- variablesFamilia$IHH_frecuencia*0.5 + 
  variablesFamilia$IHH_valor*0.5

variablesFamilia <- variablesFamilia %>% filter(numero_contratos > 20) %>%
  arrange(puntaje_concentracion)

write.csv(variablesFamilia, "variablesFamilia.csv")
```

## Resultado

```{r}
consulta1 <- BaseDatos %>% filter(nombre_familia == "Hormonas y antagonistas hormonales") %>% 
  group_by(id_contratista_2) %>% summarise(contratos = n(), valor = sum(valor_total)) %>% 
  arrange(desc(valor))
consulta1

sum(610997359622/sum(consulta1$valor))
```

