---
title: "An치lisis de Indicadores con Importancia Economica"
author: "Lizeth Jerez y Nicolas Arrieta"
date: "22/2/2020"
output: 
  html_document:
    toc: true
    number_sections: true
---

## Lectura BD

```{r warning=FALSE, error=FALSE}
library(tidyverse)
library(DT)
library(sp)
library(RColorBrewer)
library(maptools)
library(scales)
library(rgdal)
library(lubridate)
```

```{r}
BaseDatos <- read.csv(file = "AnalisisDatos\\SECOP_I_A1.CSV", stringsAsFactors = FALSE)
```


## Crecion de variables por departamento

```{r}
variablesMunicipio <- BaseDatos %>% group_by(anno_firma, municipio_ejecucion_2) %>% 
  summarise(numero_contratos = n(), 
            numero_entidades = n_distinct(nit_entidad),
            numero_contratistas = n_distinct(id_contratista_2),
            grado_importancia = mean(grado_importancia_economica),
            valor_agregado = mean(valor_agregado),
            peso_relatico_municipal = mean(peso_relatico_municipal),
            cobertura_neta = mean(cobertura_neta),
            cobertura_bruta = mean(cobertura_bruta),
            tasa_matricula = mean(tasa_matricula),
            contratos_cerrados = sum(proceso_abierto),
            contratos_adicion = sum(adicion))

variablesMunicipio$contratos_cerrados <- 1 - variablesMunicipio$contratos_cerrados/variablesMunicipio$numero_contratos

variablesMunicipio$contratos_adicion <- variablesMunicipio$contratos_adicion/variablesMunicipio$numero_contratos
```


```{r}
indice_IHH_frec_Mun <- BaseDatos %>%
      group_by(anno_firma, municipio_ejecucion_2, id_contratista_2) %>%
      summarise(total = n()) %>% 
      group_by(anno_firma, municipio_ejecucion_2) %>% 
      mutate(total_municipio = sum(total),
         indice_municipio = ((total/total_municipio)*100)^2) %>% 
      group_by(anno_firma, municipio_ejecucion_2) %>% 
      summarise(IHH_frecuencia = sum(indice_municipio))
```


```{r}

indice_IHH_valor_Mun <- BaseDatos %>%
      group_by(anno_firma, municipio_ejecucion_2, id_contratista_2) %>%
      summarise(total = sum(valor_total)) %>% 
      group_by(anno_firma, municipio_ejecucion_2) %>% 
      mutate(total_municipio = sum(total),
         indice_municipio = ((total/total_municipio)*100)^2) %>% 
      group_by(anno_firma, municipio_ejecucion_2) %>% 
      summarise(IHH_valor = sum(indice_municipio))
```

```{r}
variablesMunicipio <- merge(x = variablesMunicipio, y = indice_IHH_frec_Mun, 
                            by.x = c("anno_firma","municipio_ejecucion_2"),
                                by.y = c("anno_firma", "municipio_ejecucion_2"))

variablesMunicipio <- merge(x = variablesMunicipio, y = indice_IHH_valor_Mun, 
                            by.x = c("anno_firma","municipio_ejecucion_2"),
                                by.y = c("anno_firma", "municipio_ejecucion_2"))
```

```{r}
indice_DN_frec_Mun <- BaseDatos %>%
      group_by(anno_firma, municipio_ejecucion_2, id_contratista_2) %>%
      summarise(total = n()) %>% 
      group_by(anno_firma, municipio_ejecucion_2) %>% 
      mutate(total_municipio = sum(total),
         indice_municipio = total*(total-1)) %>% 
      group_by(anno_firma, municipio_ejecucion_2) %>% 
      summarise(DN = sum(indice_municipio)/(mean(total_municipio)*(mean(total_municipio)-1)))

variablesMunicipio <- merge(x = variablesMunicipio, y = indice_DN_frec_Mun, by.x = c("anno_firma", "municipio_ejecucion_2"),
                                by.y = c("anno_firma", "municipio_ejecucion_2"))

variablesMunicipio <- variablesMunicipio %>% filter(numero_contratos > 10)

variablesMunicipio <- variablesMunicipio %>% arrange(grado_importancia, desc(IHH_valor))

```

## Resultado

```{r}
ResumenMuni <- variablesMunicipio %>% group_by(grado_importancia) %>% 
  summarize(porcentaje_contratos_cerrado_media = mean(contratos_cerrados),
            porcentaje_contratos_cerrado_mediana = median(contratos_cerrados),
            porcentaje_contratos_adicion_media = mean(contratos_adicion), 
            porcentaje_contratos_adicion_mediana =median(contratos_adicion),
            entidades_media = mean(numero_entidades), 
            entidades_mediana = median(numero_entidades),
            contratistas_media = mean(numero_contratistas),
            contratistas_mediana = median(numero_contratistas),
            contratos_media = mean(numero_contratos),
            contratos_mediana = median(numero_contratos))

write.csv(ResumenMuni, "ResumenMuni.csv")
```


```{r}
ggplot(data = variablesMunicipio, aes(x = log(valor_agregado), y = log(IHH_frecuencia), color = anno_firma)) + geom_point()
```

```{r}
correlacion_valorAgregado <- variablesMunicipio %>% group_by(municipio_ejecucion_2) %>% 
  summarize(prom_IHH_anual_frec = mean(IHH_frecuencia),
            prom_IHH_anual_valor = mean(IHH_valor),
            valor_agregado = mean(valor_agregado),
            numero_anual_contratistas = mean(numero_contratistas),
            grado_importancia = mean(grado_importancia),
            contratos_cerrados = mean(contratos_cerrados),
            contratos_adicion = mean(contratos_adicion),
            cobertura_neta = mean(cobertura_neta),
            cobertura_bruta = mean(cobertura_bruta))

correlacion_valorAgregado[correlacion_valorAgregado$municipio_ejecucion_2 == "colombia-todoelpais",
                          c("valor_agregado", "grado_importancia")] <-     c(mean(correlacion_valorAgregado$valor_agregado, na.rm = TRUE),0)

p1 <- ggplot(data = correlacion_valorAgregado, 
       aes(x = log(valor_agregado), y = log(prom_IHH_anual_frec), color = log(cobertura_neta))) + stat_smooth(method=lm) + geom_point()

p1 <- p1 + labs(x = "valor agregado",
                y = "indice IHH frecuecia",
                colour = "grado imp.")

cor(log(correlacion_valorAgregado$valor_agregado), log(correlacion_valorAgregado$prom_IHH_anual_frec), 
    method = "pearson")
```

```{r}
p1
```

```{r}
ggsave(plot = p1, "Relacion_ValorAgregado_IHH.png", device = "png")
```


```{r}
modelo1 <- lm(log(prom_IHH_anual_frec)~log(valor_agregado),
              data = correlacion_valorAgregado) 
summary(modelo1)
```

```{r}
tapply(variablesMunicipio$contratos_cerrados,
       variablesMunicipio$anno_firma, FUN = summary)
```

```{r}
tapply(correlacion_valorAgregado$prom_IHH_anual_valor,
       correlacion_valorAgregado$grado_importancia, FUN = summary)
```

```{r}
hist(x = variablesMunicipio$contratos_cerrados, breaks = 40)
```


TOP 10

```{r}
correlacion_valorAgregado <- correlacion_valorAgregado %>% 
  mutate(puntaje = prom_IHH_anual_frec/max(correlacion_valorAgregado$prom_IHH_anual_frec)*0.25 +
                   prom_IHH_anual_valor/max(correlacion_valorAgregado$prom_IHH_anual_valor)*0.25 +
                   contratos_cerrados*0.25 +
                   contratos_adicion*0.25) %>%
            arrange(desc(puntaje))

head(correlacion_valorAgregado, 10)

for (i in 1:772) {
correlacion_valorAgregado[i, "departamento"] <- 
  {x <- strsplit(as.character(correlacion_valorAgregado[i ,"municipio_ejecucion_2"]), "-"); x[[1]][1]}
}

IHH_municipio <- correlacion_valorAgregado %>% group_by(departamento) %>% 
  summarise(IHH_fre =mean(prom_IHH_anual_frec), 
            IHH_valor = mean(prom_IHH_anual_valor), 
            puntaje_total = mean(puntaje))
```

# Mapa

```{r}
IHH_municipio <- IHH_municipio %>% arrange(departamento)
# Agregar las atenciones de Bogot치 a Cundinamarca


IHH_municipio[5, "departamento"] <- "cundinamarca"

IHH_municipio <- IHH_municipio %>% group_by(departamento) %>%
  summarise(IHH_fre = mean(IHH_fre),
            IHH_valor = mean(IHH_valor),
            puntaje_total = mean(puntaje_total))

IHH_municipio <- IHH_municipio %>% arrange(departamento)

IHH_municipio[31:32,] <- c(0,0,0,0)

IHH_municipio$id <- c(0:31)
```

```{r}
# Leer informaci칩n geografica
ohsCol2 <- readOGR("Col_Adm_1/COL_adm1.shp")
```

```{r}
ohsColI2 <- fortify(ohsCol2)
```

```{r}
mapa <- merge(ohsColI2, IHH_municipio, by = "id")
mapColDep1 <- ggplot() +
geom_polygon(data=mapa, aes(x=long, y=lat, group = group,
fill = log(Atenciones)), colour ="black", size = 0.1) +
labs(title = "Colombia", fill = "") +
labs(x="",y="",title="Log(Atenciones) en el a침o 2012") +
scale_x_continuous(limits=c(-80,-65))+
scale_y_continuous(limits=c(-5,13))

ggplotly(mapColDep1)
```

